### ISSUE TITLE
Minor Documentation Issues

### ISSUE THREAD

**Issue by da1910** [pyansys/openapi-common#152]
- [x] `ApiClient.deserialize()` - datetime classes are missing intersphinx links
- [x] `ApiException.headers` - Typo in "defeault"
- [ ] `ApiClient.call_api()` - Missing type alias for DeserializedType
- [ ] `ApiClient.sanitize_for_serialization()` - Missing type alias for DeserializedType
- [ ] `ApiClient.request()` - Missing type alias for SerializedType

**Comment by ludovicsteinbach** [comment]
I've had a look at the issues regarding type aliases.

`sphinx_autodoc_typehints` is meant to first collect and remove the type hints from the function definition, and second, to update the docstring to add the missing types. As part of this process, the aliases get replaced with the full type hint definition. However, it only supports reST formatted docstrings (e.g. `:param body: body of the request`) and we're using Numpy docstring format. The package owner has no interest in compatibility with Numpy docstrings, but users have stated that the package is compatible with `sphinx.ext.napoleon`, which can convert Numpy docstrings to reST docstrings.
We use `numpydoc` instead, which does not convert the docstrings, but formats them directly. Switching to `napoleon` is an option, but it changes the output slightly and we lose the validation provided by `numpydoc`

An alternative fix is to document the type aliases separately, so that users can click the alias and see its definition.
Illustrated in API Reference page:
![image](https://user-images.githubusercontent.com/29862462/203552087-5fa55e24-7a4f-44ce-a3d0-300d5ae8191e.png)
And in details
![image](https://user-images.githubusercontent.com/29862462/203551851-02b90c50-abfd-4d10-90ca-ede1a9a6b683.png)

It's an easy fix

**Comment by da1910** [comment]
This is probably a nicer solution for me, the documentation for the methods and classes retains the concise alias, but you can at least see what the alias is, if the links work then this is a good solution.
